version: '3'
services:
  vue-app:
    build: .
    ports:
      - "8080:8080"
    container_name: readme-vue-dev
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run serve
